/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien2;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        warnning_text = new javax.swing.JTextField();
        input_fullName = new javax.swing.JTextField();
        input_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input_address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        input_hsl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        input_exprience = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_deleteFile = new javax.swing.JButton();
        btn_addNV = new javax.swing.JButton();
        btn_saveNV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console_output = new javax.swing.JTextArea();
        input_gender = new javax.swing.JTextField();
        input_department = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("nhập thông tin nhân viên");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(25, 25, 25));
        jLabel1.setText("họ tên : ");

        warnning_text.setEditable(false);
        warnning_text.setBackground(new java.awt.Color(255, 255, 255));
        warnning_text.setForeground(new java.awt.Color(253, 0, 0));
        warnning_text.setText("xin chào");
        warnning_text.setBorder(null);
        warnning_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        input_fullName.setBackground(new java.awt.Color(255, 255, 255));
        input_fullName.setForeground(new java.awt.Color(0, 0, 0));

        input_date.setBackground(new java.awt.Color(255, 255, 255));
        input_date.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(25, 25, 25));
        jLabel2.setText("ngày sinh :");

        jLabel3.setForeground(new java.awt.Color(25, 25, 25));
        jLabel3.setText("giới tính :");

        jLabel4.setForeground(new java.awt.Color(25, 25, 25));
        jLabel4.setText("địa chỉ : ");

        input_address.setBackground(new java.awt.Color(255, 255, 255));
        input_address.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(25, 25, 25));
        jLabel5.setText("phòng ban :");

        input_hsl.setBackground(new java.awt.Color(255, 255, 255));
        input_hsl.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(25, 25, 25));
        jLabel6.setText("hệ số lương");

        input_exprience.setBackground(new java.awt.Color(255, 255, 255));
        input_exprience.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(25, 25, 25));
        jLabel7.setText("thâm niên");

        input_salary.setBackground(new java.awt.Color(255, 255, 255));
        input_salary.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(25, 25, 25));
        jLabel8.setText("lương cơ bản");

        btn_deleteFile.setBackground(new java.awt.Color(0, 0, 0));
        btn_deleteFile.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteFile.setText("xóa file");
        btn_deleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteFileActionPerformed(evt);
            }
        });

        btn_addNV.setBackground(new java.awt.Color(0, 0, 0));
        btn_addNV.setForeground(new java.awt.Color(255, 255, 255));
        btn_addNV.setText("thêm nhân viên");
        btn_addNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNVActionPerformed(evt);
            }
        });

        btn_saveNV.setBackground(new java.awt.Color(0, 0, 0));
        btn_saveNV.setForeground(new java.awt.Color(255, 255, 255));
        btn_saveNV.setText("lưu dữ liệu");
        btn_saveNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveNVActionPerformed(evt);
            }
        });

        console_output.setBackground(new java.awt.Color(102, 102, 102));
        console_output.setColumns(20);
        console_output.setForeground(new java.awt.Color(255, 255, 255));
        console_output.setRows(5);
        console_output.setText("thông tin nhân viên :");
        jScrollPane1.setViewportView(console_output);

        input_gender.setBackground(new java.awt.Color(255, 255, 255));
        input_gender.setForeground(new java.awt.Color(0, 0, 0));

        input_department.setBackground(new java.awt.Color(255, 255, 255));
        input_department.setForeground(new java.awt.Color(0, 0, 0));
        input_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiết bị", "Nhân sự", "R&D", "Kinh doanh " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(warnning_text)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input_hsl, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(input_exprience)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(input_salary))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(input_address, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                            .addComponent(input_department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(input_fullName)
                                            .addComponent(input_gender)
                                            .addComponent(input_date))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_addNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_deleteFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_saveNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(warnning_text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(input_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteFile))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(input_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(input_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_addNV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(input_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_saveNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(input_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(input_hsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_exprience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(input_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteFileActionPerformed
        // TODO add your handling code here:
        File file = new File("nhanvien1.dat");
        if (file.isFile()) {
            file.delete();
            warnning_text.setText("file đã được xóa !!");
        } else {
            warnning_text.setText("file chưa được tạo!!");
        }
    }//GEN-LAST:event_btn_deleteFileActionPerformed

    private void btn_addNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNVActionPerformed
        // TODO add your handling code here:
        if (input_fullName.getText().equals("")
                || input_address.getText().equals("")
                || input_gender.getText().equals("")
                || input_date.getText().equals("")
                || input_department.getSelectedItem().toString().equals("")
                || input_exprience.getText().equals("")
                || input_hsl.getText().equals("")
                || input_salary.getText().equals("")) {
            warnning_text.setText("bạn chưa điền hết thông tin");
        } else {
            Employee nv = new Employee();
            nv.setFullName(input_fullName.getText());
            nv.setAddress(input_address.getText());
            nv.setGender(input_gender.getText());
            nv.setDate(input_date.getText());
            nv.setDepartment(input_department.getSelectedItem().toString());
            nv.setExperience(Byte.parseByte(input_exprience.getText()));
            nv.setHsl(Float.parseFloat(input_hsl.getText()));
            nv.setSalary_basic(Double.parseDouble(input_salary.getText()));
            nv.add(nv);
            console_output.setText(console_output.getText() + "\n" + nv.toString());
            nv.display();
            // reset
            input_fullName.setText("");
            input_address.setText("");
            input_date.setText("");
            input_exprience.setText("");
            input_gender.setText("");
            input_hsl.setText("");
            input_salary.setText("");
            JOptionPane.showMessageDialog(null, "Them Thanh Cong!");
            warnning_text.setText("bạn đã thêm sinh viên thành công");
        }
    }//GEN-LAST:event_btn_addNVActionPerformed

    private void btn_saveNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveNVActionPerformed
        // TODO add your handling code here:
        Employee nv = new Employee();
        String information = nv.getInfoNV();
        FileWriter fileWriter = null; 
        System.out.println(information);
        try {
            if(information == ""){
                warnning_text.setText("bạn phải ấn vào thêm sinh viên trước đã!!!");
            } else {
                fileWriter = new FileWriter("nhanvien1.dat", true);
                fileWriter.write(information);
                JOptionPane.showMessageDialog(null, "lưu thông tin thành công!");
                warnning_text.setText("bạn đã lưu toàn bộ thông tin thành công !!");
            }
        } catch (HeadlessException | IOException e) {
        } finally {
            if(fileWriter != null){
                try {
                    fileWriter.close();
                } catch (IOException ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_saveNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addNV;
    private javax.swing.JButton btn_deleteFile;
    private javax.swing.JButton btn_saveNV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea console_output;
    private javax.swing.JTextField input_address;
    private javax.swing.JTextField input_date;
    private javax.swing.JComboBox<String> input_department;
    private javax.swing.JTextField input_exprience;
    private javax.swing.JTextField input_fullName;
    private javax.swing.JTextField input_gender;
    private javax.swing.JTextField input_hsl;
    private javax.swing.JTextField input_salary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField warnning_text;
    // End of variables declaration//GEN-END:variables
}
